"gvim settings
set guifont=Monospace\ 11
colorscheme darkspectrum
" colorscheme solarized
"
noremap = :LargerFont<CR>
noremap - :SmallerFont<CR>
"noremap  <C-->      :SmallerFont<CR>
"inoremap <C-->      <C-C>:SmallerFont<CR>
"noremap  <C-=>      :LargerFont<CR>
"inoremap <C-=>      <C-C>:LargerFont<CR>
"
" Change font size
" http://vim.wikia.com/wiki/Change_font_size_quickly

let s:pattern = '^\(.* \)\([1-9][0-9]*\)$'
let s:minfontsize = 6
let s:maxfontsize = 30

function! AdjustFontSize(amount)
if has("gui_gtk2") && has("gui_running")
  let fontname = substitute(&guifont, s:pattern, '\1', '')
  let cursize = substitute(&guifont, s:pattern, '\2', '')
  let newsize = cursize + a:amount
  if (newsize >= s:minfontsize) && (newsize <= s:maxfontsize)
    let newfont = fontname . newsize
    let &guifont = newfont
  endif
else
  echoerr "You need to run the GTK2 version of Vim to use this function."
endif
endfunction


function! LargerFont()
    call AdjustFontSize(1)
endfunction
command! LargerFont call LargerFont()

function! SmallerFont()
    call AdjustFontSize(-1)
endfunction
command! SmallerFont call SmallerFont()
"Chaning fonts with + - in gui :D
let s:defaultfontsize = substitute(&guifont, s:pattern, '\2', '')

function! SetFontSize(the_size)
    if has("gui_gtk2") && has("gui_running")
        let fontname = substitute(&guifont, s:pattern, '\1', '')
        let newfont = fontname . a:the_size
        let &guifont = newfont
    else
        echoerr "You need to run the GTK2 version of VIM to use this function."
    endif
endfunction

command! DefaultFont call SetFontSize(s:defaultfontsize)
"noremap <C>0 :DefaultFont<CR>
