#!/bin/bash
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$HOME/.local/bin:$HOME/bin:$PATH
export PATH


# Cuda installation
if [ -d /usr/local/cuda-9.0/bin ]; then
    export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
fi

export USE_CCACHE=1

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*


# my own alias
# If this is before the rvm script call, this will cause an annoying error
alias cd='cd -P'
