#!/bin/bash
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  source /etc/bashrc
fi

# User specific aliases and functions
if [ -f ~/.bash_aliases ]; then
  source ~/.bash_aliases
fi

# No color + GIT
#PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
# Color + GIT
GIT_PS1='\[\e[0m\][\[\e[0;34m\]\u\[\e[0m\]@\[\e[0;32m\]\h\[\e[0m\] \[\e[0;35m\]\W$(__git_ps1 "\[\e[0m\] \[\e[0;36m\](%s)")\[\e[0m\]]\$ '

# Fedora
if [ -f  /usr/share/git-core/contrib/completion/git-prompt.sh ]; then
  source /usr/share/git-core/contrib/completion/git-prompt.sh
  PS1=$GIT_PS1
fi

# Ubuntu
if [ -f /etc/bash_completion.d/git-prompt ]; then
  source /etc/bash_completion.d/git-prompt
  PS1=$GIT_PS1
fi


export TERM=gnome-256color

export EDITOR=vim

export QT_GRAPHICSSYSTEM=native

# for packaging RPMs
export RPM_PACKAGER='Mark Harfouche <mark.harfouche@gmail.com>'

# Ignore duplicates in bash history
export HISTCONTROL=ignoredups:erasedups

# send in Ctrl-s to vim
# see http://unix.stackexchange.com/questions/12107/how-to-unfreeze-after-accidentally-pressing-ctrl-s-in-a-terminal
stty stop undef
stty -ixon
stty 115200

# added by Miniconda3 installer
export PATH="$HOME/miniconda3/bin:$PATH"
