# .bash_profile

if [ -f /etc/profile ]; then
  . /etc/profile
fi

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin
export PATH



[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*


# my own alias
# If this is before the rvm script call, this will cause an annoying error
alias cd='cd -P'
