#!/bin/bash
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

# Don't know why this isn't working anymore
module load mpi/mpich-x86_64

PATH=$PATH:$HOME/.local/bin:$HOME/bin
export PATH

## export JAVA_HOME JDK/JRE ##
#export JAVA_HOME="/usr/java/latest"
#export MATLAB_JAVA="/usr/java/latest/jre/"
#https://wiki.archlinux.org/index.php/awesome#Grey_Java_GUIs
#export _JAVA_AWT_WM_NONREPARENTING=1

export USE_CCACHE=1


[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*


# my own alias
# If this is before the rvm script call, this will cause an annoying error
alias cd='cd -P'
